### ISSUE TITLE
Remove "Delegate" tab from Manager address view

### ISSUE THREAD

**Issue by polinasoshkina** [Cryptonomic/Tezos-Wallet#105]
- [ ] Remove "Delegate" tab from Manager address

Design:
https://zpl.io/2EARjA8

**Comment by polinasoshkina** [comment]
@rafcamlet 
- [ ] there is a bug with delegate tab. If I switch to Delegated Address and go to "Delegate" tab there and then switch to "Manager Address" I see the following:
![image](https://user-images.githubusercontent.com/4014197/42197647-ce282520-7e51-11e8-9c82-327c0a481d50.png)

**Comment by bpawinski** [comment]
@polinasoshkina Could you describe how this should work?

**Comment by polinasoshkina** [comment]
I am moving this to another ticket. This issue is bigger than delegate tab.
