### ISSUE TITLE
Display the full address balance in the sidebar.

### ISSUE THREAD

**Issue by polinasoshkina** [Cryptonomic/Tezos-Wallet#107]
- [ ] Right now we are rounding the address balances in the sidebar and displaying the hover tooltip. Instead please display all 6 decimal places and disable the tooltip. 

Design:
https://zpl.io/boxM9WW

**Comment by polinasoshkina** [comment]
The font is too big, it breaks the layout when the account is syncing. Please make sure that the font size matches the design.

**Comment by polinasoshkina** [comment]
@mikaScalac 
- [ ] Only address balances should be displayed in full, the account balance should be rounded up to 2 decimal places and be displayed with a tooltip.
- [ ] Please check the font sizes in the design. Address balance is 14 while Account balance is 16.

**Comment by mikaScalac** [comment]
![image](https://user-images.githubusercontent.com/40353522/42205278-48cd4bd2-7ea4-11e8-9efb-5d236bd9b121.png)
