### ISSUE TITLE
Add Terms of Service and Privacy Policy overlay and persistent checkbox.

### ISSUE THREAD

**Issue by polinasoshkina** [Cryptonomic/Tezos-Wallet#115]
- [ ] First-time wallet user should see Terms of Service and Privacy Policy overlay that should prevent the user from using the app unless s/he clicks on the "I Agree" button.
- [ ] Once the user clicks on the "I agree" button, the overlay goes away and checkbox with "I acknowledge" text is displayed in the footer of the landing page. The checkmark is checked and Terms of Service and Privacy Policy are linked.
- [ ] If the user unchecks the checkbox all the buttons become disabled so that user cannot use the wallet.
- [ ] The user can always check the checkbox again to enable the wallet app.
Design:
https://zpl.io/VxYwn5W
https://zpl.io/VDzWDm3

**Comment by vishakh** [comment]
Done
