### ISSUE TITLE
If you import a wallet file and enter wrong password, app freezes

### ISSUE THREAD

**Issue by csoreff** [Cryptonomic/Tezos-Wallet#117]
If I enter a wrong password when importing wallet file, the app freezes.  Can't do anything, need to force close the app.  It hangs in a loading state with spinner.  

This should display an error message if password is incorrect and allow user to try again.

<img width="1025" alt="screen shot 2018-06-27 at 11 27 56 am" src="https://user-images.githubusercontent.com/6821977/41965604-3b2c1b6c-79fd-11e8-8e61-c2c78453ddd9.png">

**Comment by vishakh** [comment]
This should be addressed by https://github.com/Cryptonomic/ConseilJS/issues/22

**Comment by vishakh** [comment]
We will move to a new version of ConseilJS shortly.
