### ISSUE TITLE
Add Node Settings

### ISSUE THREAD

**Issue by polinasoshkina** [Cryptonomic/Tezos-Wallet#126]
- [ ] Add back in the settings icon to the header 
- [ ] Settings icon should take you to the Wallet Settings screen
- [ ] Under wallet setting display Node settings (dropdowns for Conseil and Tezos)
- [ ] Each dropdown should have "Add a Custom Node" option.
- [ ] There are two modals for the creation of custom nodes (one for Conseil and one for Tezos)
- [ ] we are allowing both HTTPS and HTTP nodes
- [ ] the settings screen should have "back to wallet" link that takes the user back to their accounts view.

Nodes for launch:
tezos node: blockscale (node.tzbeta.net)
cosneil node: cryptonomic (conseil-prod.cryptonomic-infra.tech)

Designs:
https://zpl.io/a8KJWeg
https://zpl.io/VOk1B7l
https://zpl.io/bLO1NE6
https://zpl.io/bJq1NxD

**Comment by vishakh** [comment]
No node addresses should be hard coded. Instead, the settings screen should be blank by default and the wallet unusable. A developer or packager should be required to list the available nodes in a JSON file at a fixed location (outside of source control) if they want presets to be populated into the settings screen.

**Comment by abrakadobr** [comment]
ok, i'm really happy that "nothig should be hardcoded" but still you don't provide any other options =(

**Comment by vishakh** [comment]
@abrakadobr What other options would you like?

(Sorry if you have told us before but we are working on multiple things and lose context often.)
