### ISSUE TITLE
Bug: disappearing transactions in delegated address transactions tab

### ISSUE THREAD

**Issue by polinasoshkina** [Cryptonomic/Tezos-Wallet#132]
1. Create a delegated address
2. Send some tez from delegated address to the manager
3. Wait for the transaction to appear
4. Wait a bit longer to see it disappear and be again replaced with no transactions screen.

**Comment by umurb** [comment]
Transactions are still disappearing in delegated addresses after each refresh. Reopening this issue.

**Comment by umurb** [comment]
Here is a screen recording;

![disappearing transactions](https://user-images.githubusercontent.com/37525692/42577356-1f730840-84f2-11e8-9472-7f462e9118ba.gif)

**Comment by umurb** [comment]
merged with #212 closing
