### ISSUE TITLE
Any way of using cusom nodes

### ISSUE THREAD

**Issue by abrakadobr** [Cryptonomic/Tezos-Wallet#133]
Hello!
is there any "official" way of using custom nodes now?
in current version "settings" button don't react at all, and I want to use wallet with my node.
some ENV settings, maybe? or can you point me to file, i have to change before compilation to get my wallet compiled for custom node?
this issue is related to #126 , but I don't care about nice UI and looking for any way of setting custom node now.

**Comment by abrakadobr** [comment]
looks like found it in app/utils/NautilusQuery,js
looks like it requires special "http proxy" to rebuild query params to node - isn't it?

**Comment by abrakadobr** [comment]
so, what i found afterall, if someone would be interested to experiment before #126 done
1. edit dll/dev.renderer.dll.js at line 838 `const url = `http://${server}/${route}`` to ``const url = `http://localhost:8732/${route}``` (or set your's network settings) - this is easiest way to hardcode goal
2. but this will not help you now (at 29/06), cuz zeronet updates faster whan wallet =))))

**Comment by vishakh** [comment]
@abrakadobr We are adding a settings screen and the ability to use custom servers. See #126.

**Comment by vishakh** [comment]
Addressed by #126
