### ISSUE TITLE
Overflow in button on Create Wallet screen

### ISSUE THREAD

**Issue by grimpil** [Cryptonomic/Tezos-Wallet#134]
Steps to reproduce:
- Hit the "Create Wallet" button on the launch screen

(MacOS 10.12.6)

<img width="1027" alt="screen shot 2018-06-29 at 01 38 35" src="https://user-images.githubusercontent.com/7773941/42076090-a5c95a9e-7b41-11e8-85f3-4f06785a2381.png">

**Comment by vishakh** [comment]
Could not replicate.
