### ISSUE TITLE
Bug: Clicking on a node selection makes the app go blank

### ISSUE THREAD

**Issue by polinasoshkina** [Cryptonomic/Tezos-Wallet#146]
1. Go to settings
2. Click on Conseil dropdown
3. Select Cryptonomic
4. Watch the screen become completely white

After I click here on Cryptonomic-Conseil:
![image](https://user-images.githubusercontent.com/4014197/42198529-70df6482-7e56-11e8-860e-1c7e75e10f9c.png)
the screen just goes white:
![image](https://user-images.githubusercontent.com/4014197/42198549-8c2e67ec-7e56-11e8-98be-c862b7b9b4cc.png)

**Comment by mikaScalac** [comment]
I was trying to reproduce this bug but on actual develop everything looks fine

**Comment by vishakh** [comment]
Cannot be reproduced.
