### ISSUE TITLE
Layout fix: On settings node selection when the screen is narrow node URLs get cut-off.

### ISSUE THREAD

**Issue by polinasoshkina** [Cryptonomic/Tezos-Wallet#147]
- [ ] drop node URLs to the second line

**Comment by polinasoshkina** [comment]
@yanivkalfa Here is where URLs don't fit into the drop-downs
![image](https://user-images.githubusercontent.com/4014197/42198377-b4d25236-7e55-11e8-8333-d7ff6a7a4b97.png)
Is this an actual Cryptonomic Conseil node URL or is it going to be shorter?

**Comment by mikaScalac** [comment]
![image](https://user-images.githubusercontent.com/40353522/42218335-861920b4-7ec8-11e8-9569-02ae0251b393.png)

**Comment by yanivkalfa** [comment]
@polinasoshkina i dont think they are going to be any shorter.

**Comment by polinasoshkina** [comment]
which branch is this?

**Comment by vishakh** [comment]
Merged
