### ISSUE TITLE
Add back buttons to Create and Open wallet forms

### ISSUE THREAD

**Issue by polinasoshkina** [Cryptonomic/Tezos-Wallet#148]
- [x] Add "Back" link to Create New Wallet screen, that takes the user back to the landing page
- [x] Add "Back" link to Open Existing Wallet screen, that takes the user back to the landing page

Design:
https://zpl.io/VYBXP6e

**Comment by mikaScalac** [comment]
![backbutton](https://user-images.githubusercontent.com/40353522/42216002-94216a5c-7ec0-11e8-9384-6c501ee19cec.gif)
