### ISSUE TITLE
Expose operation IDs for the creation of accounts and addresses.

### ISSUE THREAD

**Issue by polinasoshkina** [Cryptonomic/Tezos-Wallet#149]
Display Operation IDs and operation names for the following:

### Loading fundraiser identity:

1. activation https://zpl.io/VDz0mQg
2. fetching from blockchain (we might want to still keep activation ID up just so that they have something to check last sussessful operation, but I am ok with getting rid of it as well) https://zpl.io/VxYZ9qW
3. key reveal https://zpl.io/a8K0Dqx
4. Account ready (dissapears in a couple of seconds) https://zpl.io/blpYenP
5. Fade in all the account info and enable all functions https://zpl.io/V0yBzOw

### Loading new tz1 address (from mnemonic):

1. Create an account (we might not display any messaging if it just takes a second) https://zpl.io/bAq1KMq
2. Show that the account is not revealed yet https://zpl.io/agvJ1AN
3. Once we get the first transaction trigger key reveal and message out that the account is getting ready. https://zpl.io/aRYpwON
4. Account ready (dissapears in a couple of seconds) https://zpl.io/2ZJN3dL
5. Fade in all the account info and enable all functions https://zpl.io/b6M05YK

### Creating new kt1:
origination operation
key reveal

Designs in sequence (what it looks like if you don't open that address):
https://app.zeplin.io/project/5b1752dd44fc7a0363cd9dc8/dashboard?seid=5b4261e44db03a81650d1eb1

If you click on KT1 it should be displaying the same way as syncing is displaying for the fundraiser. The only difference that we'll be showing origination operation id under "Creating your account..." in the transactions tab space.

**Comment by umurb** [comment]
**Loading Fundraiser Identity**
Works fine. Skips two steps detailed in Zeplin but I think it is OK for now.
Skips activation step and starts with retrieving your account step.
Skips account ready step.

**Creating new kt1 address**
Works fine. Skips the same steps as fundraiser.

Not closing this ticket just yet as I couldn't test it with creating an account from mnemonic. Keeping it in Ready For Testing until #194 is fixed

**Comment by umurb** [comment]
I am now capable of creating an address from mnemonic. Revealing Operation ID worked just fine.

In all three cases, 'Creating Your Account' and 'Your Account is Ready' scenes are skipped, but I think it is perfectly fine. Closing this issue.
