### ISSUE TITLE
Correctly brand the wallet

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/Tezos-Wallet#203]
- [x] In `config.json` change the value of `name` to `Tezori`.
- [x] In `config.json` change the value of `version` to `0.1.0`.
- [x] In `config.json` add a key called `tagline` with the value `A community wallet for Tezos`
- [x] Look for all references to the string 'Galleon' and change it to `name` from `config.json`
- [x] If this is not the case already, the app titlebar should also be using `name` from the config file
- [x] Change `<AppSubtitle>Beta Wallet for Tezos Betanet</AppSubtitle>` in `app/containers/LoginHome/index.js` to use the `tagline` value.

After this change, there should be no hard coded instances of the string 'Galleon' left. At the moment, there are two instances in `app/containers/LoginHome/index.js`.

**Comment by umurb** [comment]
Merged with #205 
Note: A hard restart to the wallet is required for the changes in the title bar to take effect
