### ISSUE TITLE
As a user, I want a clear and secure way of creating and encrypting my wallet file.

### ISSUE THREAD

**Issue by polinasoshkina** [Cryptonomic/Tezos-Wallet#30]
The current flow with "select file" could be confusing to the user. We need a different flow that makes it clear that the new file will be generated and what it is for. At the same time, we need to comply with security audit requirements.

We also need to provide messaging around password creation, so that the user is aware of what it is for. 

Please use a slug library to ensure that regardless of what the user inputs into "Name Your Wallet File" field we can transform it into a proper file name.

However, if the part where a user names the file and then picks a directory becomes too complicated implementation wise please let me know and we can scale back the design.

Zeplin Designs:
https://app.zeplin.io/project/5b1752dd44fc7a0363cd9dc8/dashboard?seid=5b2c8d534b04d64da0bc8e78

**Comment by vishakh** [comment]
Closing because this seems obsolete. Let me know if you want to reopen.
