### ISSUE TITLE
As a user, I want my newly generated seed phrase to be formatted in such a way so it's easy to write down and cross-reference.

### ISSUE THREAD

**Issue by polinasoshkina** [Cryptonomic/Tezos-Wallet#32]
Currently, we just show a space-delimited string, but that will cause a lot of mistakes when people will be writing it down. Human eye frequently loses track of the last word. This way the user is prone to miss a word or mix up the order.

We should display the seed phrase in easy to read numbered grid.

+ Display Seed Phrase in a grid
+ Allow the user to generate a different one

Designs:
https://app.zeplin.io/project/5b1752dd44fc7a0363cd9dc8/dashboard?seid=5b2c9c408eac4a6376e1d194

**Comment by andrewjcasal** [comment]
@developer0623 Significant work already done in this branch feat/seedGrid.
