### ISSUE TITLE
As a user, I want backup verification for my new seed phrase as I create an account.

### ISSUE THREAD

**Issue by polinasoshkina** [Cryptonomic/Tezos-Wallet#33]
We need to include backup verification for newly generated seed phrases. We can do by asking the user to type in the n-th word from the seed phrase after it was generated. The number of values for n depends on the level of security we want (2-word minimum and maximum entire phrase).

Let's do 4 words verification.

Design:
https://app.zeplin.io/project/5b1752dd44fc7a0363cd9dc8/dashboard?seid=5b2c9c408eac4a6376e1d194

**Comment by andrewjcasal** [comment]
@developer0623 Significant work already done in this branch feat/seedGrid.
