### ISSUE TITLE
As a user, I want to see a total balance for each account

### ISSUE THREAD

**Issue by polinasoshkina** [Cryptonomic/Tezos-Wallet#46]
The total balance of all the addresses for an account is displayed next to an Account label. Keep in mind that Tezos balances can have up to 6 decimal places. We are rounding the number to two decimal places and showing that it's approximate by adding "~" in front of the number. On hover, we should display the full balance and a copy button.

![image](https://user-images.githubusercontent.com/4014197/41893578-44bb1c28-78ea-11e8-9a09-6f24eecbd0fa.png)

Design:
https://zpl.io/2EAReXY

**Comment by vishakh** [comment]
Done
