### ISSUE TITLE
Limit account import/creation to only two tabs and fix language and add tooltips

### ISSUE THREAD

**Issue by polinasoshkina** [Cryptonomic/Tezos-Wallet#78]
- [x] Remove mnemonic and key pair tabs from Add an Account screen. 
- [x] Rename "Import Fundraiser" tab to "Import Fundraiser Wallet"
- [x] Change Import fundraiser instructional text to "Please refer to the PDF document that you created during the Fundraiser."
- [x] Use proper field labels: 15 Word Secret Key, Fundraiser Password, Fundraiser Email Address, KYC/AML Activation Code.
- [x] Add tooltips to Fundraiser Password, Fundraiser Email Address, and KYC/AML Activation Code. (text provided below)

**Fundraiser Password Tooltip:** 
This is the password that you used when generating a Tezos paper wallet to participate in the Fundraiser. 
**Email Tooltip:**
This is the email address that you used when generating a Tezos paper wallet to participate in the Fundraiser.
**KYC/AML Activation Code Tooltip:** 
This is the activation code that you received after completing the KYC/AML process. An activation code corresponds to a public key hash and is required if you participated in the Fundraiser. You may complete the process at [verification.tezos.com](url) if you have not done so already.

Designs:
https://zpl.io/blpj4o0
https://zpl.io/2ZJDxYE

**Comment by polinasoshkina** [comment]
1. It still says “Add an Address” instead of “Add an Account” - please see the design
2. When entering the seed phrase when the phrase uses longer words it doesn’t all fit in and gets cut off, there is no way to scroll inside the input field to see the beginning of your seed phrase.
3. When entering an email that is too long it shows up under the question mark icon instead of being pushed back like the seed phrase. Text should not be appearing under that icon. We should treat it as if the input field is shorter.
4. Activation code field can be a little bit narrower to give email field more space
5. The website (verification.tezos.com) mentioned in the KYC/AML activation code tooltip should be linked.

**Comment by polinasoshkina** [comment]
@mikaScalac 
- [ ] When I switch between "Import Fundraiser Wallet and "Create New Account" tabs it clears my Fundraiser secret key. 
- [ ] The fields right now are not aligned and displayed in diagonal zig-zag fashion. Please make the pkh field the same width as Activation Code for now. We'll fix this layout later with another ticket.
![image](https://user-images.githubusercontent.com/4014197/42197088-29fa1302-7e4f-11e8-8cba-0add28c1e34c.png)
- [ ] Activation Code label reverted back to "KYC/AML Activation Code". Please remove "KYC/AML" part of the label.

**Comment by mikaScalac** [comment]
![image](https://user-images.githubusercontent.com/40353522/42216112-fa14e154-7ec0-11e8-89b1-4ca19cd2d4b9.png)

**Comment by mikaScalac** [comment]
![image](https://user-images.githubusercontent.com/40353522/42202919-798e61ea-7e9d-11e8-883f-7dc012fdd16c.png)

**Comment by bpawinski** [comment]
In fix layout ready to merge
