### ISSUE TITLE
Fix "Add a Delegate" form (what used to be "Add a Smart Address" form)

### ISSUE THREAD

**Issue by polinasoshkina** [Cryptonomic/Tezos-Wallet#81]
- [x] Change labels to match the design
- [x] Add tooltip for "Delegate Address" field
- [x] Remove confirm passphrase field
- [x] Do not set the user's Manager Address as the default. Keep that field empty and just don't let them create an address unless they set it to something.

Designs:
https://zpl.io/blpMnKG
https://zpl.io/aMqpYKo

**Comment by vishakh** [comment]
Completed
