### ISSUE TITLE
Can’t click and drag to select text on wallet addresses, it drags the entire application instead of selecting text.

### ISSUE THREAD

**Issue by polinasoshkina** [Cryptonomic/Tezos-Wallet#95]

**Comment by polinasoshkina** [comment]
I still can't drag and select the address, the entire application gets dragged instead. We should only have a small horizontal area in the application header that drags the entire app. Furthermore, now when I double click to select the address only a part of address gets selected. I understand that you wrapped tz1 in an HTML element to make it bold but that should not be resulting in this behavior. I tried doing this in JsFiddle and selection seems to work fine for elements wrapped in spans and even in divs if I set the display to inline. Also, the copy button next to address doesn't copy the address.

**Comment by polinasoshkina** [comment]
- [ ] When clicking on copy icon there is no indication that the text is copied (see copy button in the Receive tab)
- [ ] I still can't drag and select the address, the entire application gets dragged instead. We should only have a small horizontal area in the application header that drags the entire app.

**Comment by mikaScalac** [comment]
![image](https://user-images.githubusercontent.com/40353522/42208287-22fe0ff6-7eac-11e8-923e-57b151b7b90f.png)
![image](https://user-images.githubusercontent.com/40353522/42208312-2f4daf64-7eac-11e8-82ee-50423869869d.png)

I still looking for the solution of this drag issue

**Comment by bpawinski** [comment]
Already fixed and merged
